package by.epam.jwdsc.controller.command;

public enum CommandName {
    DEFAULT,CHANGE_LOCALE, GOTO_MAIN_PAGE, GOTO_CHECK_ORDER_PAGE, SEND_CODE, FIND_ORDER_BY_NUMBER,
    GOTO_ERROR_PAGE, GOTO_LOGIN_PAGE, LOGIN, GOTO_REGISTRATION_PAGE, LOGOUT
}
