package by.epam.jwdsc.controller.command;

public enum CommandName {
    CHANGE_LOCALE, GOTO_MAIN_PAGE, GOTO_CHECK_ORDER_PAGE, SEND_CODE, FIND_ORDER_BY_NUMBER,
    GOTO_ERROR_PAGE, GOTO_LOGIN_PAGE, LOGIN, GOTO_REGISTRATION_PAGE, LOGOUT, GOTO_CONTROL_PAGE, FIND_ORDERS,
    FIND_ALL_COMPANIES_DEVICES, FIND_CLIENTS_BY_PHONE, FIND_CLIENT_BY_ID, SAVE_NEW_ORDER, FIND_ORDER_BY_ID,
    FIND_ALL_SELECTABLE_ITEMS, FIND_PARTS_BY_PARAM, FIND_WORK_COST, UPDATE_ORDER, REMOVE_ORDER_BY_ID,
    TAKE_ORDER_TO_WORK, ISSUE_ORDER, FIND_EMPLOYEES, CHANGE_EMPLOYEE_ROLE, CHECK_LOGIN, REGISTER_EMPLOYEE,
    REGISTRATION_FIRST_STEP, REGISTRATION_FINAL, ADD_NEW_PART, FIND_PARTS, FIND_DEVICES, ADD_NEW_DEVICE
}
